### ISSUE TITLE
Corrupted file queue leading to null pointer dereference

### ISSUE THREAD

**Issue by Johnnydouble** [Johnnydouble/FileMango#6]
Something is breaking the file queue by not properly writing new lines to it in some cases.
This leads to invalid file paths in the file queue. 
It eventually leads to to a null pointer defeference in worker_pool.go and the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x595d6a]

goroutine 1 [running]:
os.(*File).Name(...)
        /usr/lib/go/src/os/file.go:54
FileMango/src/scheduler.(*fileQueue).addNewJobs(0x741ec0, 0xc00011a180)
        /home/melkor/go/src/FileMango/src/scheduler/worker_pool.go:124
```

**Comment by Lexicon9** [comment]
the entries in this test case did not have a new line character at the end of the line so was interpreted as being empty, the solution might be to check if there is anything on the current line before appending to it, or just make it clear that if manually editing the queue file the must be a new line after each path
